Database:
  #Player data storage type, MYSQL or SQLITE
  Type: SQLITE
  MYSQL:
    Host: localhost
    Port: 3306
    Database: InteractionVisualizer
    Username: mysql
    Password: password

Messages:
  NoPermission: "&cYou do not have permission to use that command!"
  Reload: "&aInteractionVisualizer sucessfully reloaded!"
  Toggle:
    Usage: "&cUsage: /interactionvisualizer toggle <itemstand/itemdrop/hologram>"
    Modes: "&cToggle Modes: itemstand, itemdrop, hologram"
    Console: "&cPlease provide a player name: /interactionvisualizer toggle <mode> [player]"
    ToggleOn: "&aToggled %s on"
    ToggleOff: "&eToggled %s off"
    PlayerNotFound: "&cThe player is not online!"

GarbageCollector:
  #How often should the plugin sweep up and remove tile entity blocks that no longer needs to be tracked
  #Measured in ticks, 20 ticks = 1 second
  #Adjust this if your server is unable to handle fast updates
  Period: 600

TileEntityUpdate:
  #How fast should the plugin collect changes to tile entities since the last check
  #The plugin will first collect all active chunks (3x3 chunk around every player)
  #Then load all the tile entities in those chunks in async
  #Note that the period is not just ChunksPerTick, it is a few ticks longer than that to deal with other things
  #Adjust this if your server is unable to handle fast updates
  ChunksPerTick: 4
  #Only turn this to false if you are having problems
  LoadTileEntitiesAsync: true

#Enable InteractionVisualizer for these blocks
Blocks:
  Anvil:
    Enabled: true
  Beacon:
    Enabled: true
    #How often should the plugin check for block updates
    #Measured in ticks, 20 ticks = 1 second
    #Adjust this if your server is unable to handle fast updates / can handle faster updates
    CheckingPeriod: 20
  BlastFurnace:
    Enabled: true
    CheckingPeriod: 20
  BrewingStand:
    Enabled: true
    CheckingPeriod: 20
  CartographyTable:
    Enabled: true
  Chest:
    Enabled: true
  CraftingTable:
    Enabled: true
  DoubleChest:
    Enabled: true
  EnchantmentTable:
    Enabled: true
  EnderChest:
    Enabled: true
  Furnace:
    Enabled: true
    CheckingPeriod: 20
  Grindstone:
    Enabled: true
  JukeBox:
    Enabled: true
    CheckingPeriod: 20
  Loom:
    Enabled: true
  NoteBlock:
    Enabled: true
  Smoker:
    Enabled: true
    CheckingPeriod: 20
  Stonecutter:
    Enabled: true
  ShulkerBox:
    Enabled: true

Entities:
  Villager: 
    Enabled: true

#Enable these modules for InteractionVisualizer displays
#ItemStand represents all displays using armorstands and itemframes
#ItemDrop represents all displays using dropped items
#Hologram represents all holograpgic displays using armorstands
Modules:
  ItemStand:
    Enabled: true
  ItemDrop:
    Enabled: true
  Hologram:
    Enabled: true

Options:
  Updater: true
  DownloadLanguageFiles: true
  
